### ISSUE TITLE
Fix for phantomjs 2.1.1 crash at startup on Windows 10.

### ISSUE THREAD

**Issue by ghts** [benbjohnson/phantomjs#10]
I don't have any  open source contribution experience, 
don't know how to create patch file.
Sorry for inconvenience

Here is fix

func (p *Process) Open() error {
     (...)
// Follwing line cause crash.
//   cmd.Env = []string{fmt.Sprintf("PORT=%d", p.Port)}   // original code

// After slight modification into next line into this one, there is no more crash.
   cmd.Env = append(os.Environ(), fmt.Sprintf("PORT=%d", p.Port)) // fixed code
     (...)
}

Thank you.

.

**Comment by Bingordinary** [comment]
> 
> 
> I don't have any open source contribution experience,
> don't know how to create patch file.
> Sorry for inconvenience
> 
> Here is fix
> 
> func (p *Process) Open() error {
> (...)
> // Follwing line cause crash.
> // cmd.Env = []string{fmt.Sprintf("PORT=%d", p.Port)} // original code
> 
> // After slight modification into next line into this one, there is no more crash.
> cmd.Env = append(os.Environ(), fmt.Sprintf("PORT=%d", p.Port)) // fixed code
> (...)
> }
> 
> Thank you.
> 
> .

I got the same error while running phantomjs 2.1.1 in windows 10, and I have fixed it by using your code. 
It is work! Thank you!

**Comment by benbjohnson** [comment]
I'm closing this issue and archiving the repository as phantomjs has been deprecated since 2018. https://github.com/benbjohnson/phantomjs#deprecation-warning
