### ISSUE TITLE
How to use proxy? thanks

### ISSUE THREAD

**Issue by amnotbusy** [benbjohnson/phantomjs#4]
How to use proxy? thanks

**Comment by MikhailKlemin** [comment]
I thought about this as well. 
It is not implemented in the package, but it seems like posisble just to add a cmd.Env for "http_proxy" however I have not tested it. 
From phantomjs.go:  

```
// Start external process.
cmd := exec.Command(p.BinPath, scriptPath)
cmd.Env = []string{fmt.Sprintf("PORT=%d", p.Port)}
```		
So just change to 
```
// Start external process.
cmd := exec.Command(p.BinPath, scriptPath)
cmd.Env = []string{fmt.Sprintf("PORT=%d", p.Port), "http_proxy=192.168.1.4:8000", "HTTPS_PROXY=192.168.1.4:8000"}
```		
Or just implement phantomjs --proxy in the code.

**Comment by ego008** [comment]
I have added some `setProxy` functions in my fork https://github.com/ego008/gophantomjs

**Comment by benbjohnson** [comment]
I'm closing this issue and archiving the repository as phantomjs has been deprecated since 2018. https://github.com/benbjohnson/phantomjs#deprecation-warning
