### ISSUE TITLE
Evaluate function()

### ISSUE THREAD

**Issue by MorrisLaw** [benbjohnson/phantomjs#6]
Is it possible to return a group of css selectors from this function then pass it back into another Evaluate function later on ? Or an equivalent workaround ? Thank you.

**Comment by benbjohnson** [comment]
The returned value from your function is JSONified and returned. You could embed that in a second eval script later on.

https://github.com/benbjohnson/phantomjs/blob/master/phantomjs.go#L1614-L1620

You may also be able to set the value on a property of `window` on your first eval & reference that on your second eval.

**Comment by MorrisLaw** [comment]
Thank you for the explanation @benbjohnson !
