### ISSUE TITLE
Not working over SSL

### ISSUE THREAD

**Issue by incrementing** [benbjohnson/phantomjs#9]
When I make requests over SSL I get an error, I've tried using page.SetSettings but I can't find a setting that ignores SSL errors or something along those lines.
```golang
// Works fine, loads the page, etc.
if err := page.Open("http://whatsmyuseragent.org"); err != nil {
    panic(err)
}

// err isn't nil
if err := page.Open("https://google.com"); err != nil {
    panic(err)
}
```

Stacktrace:
```
panic: failed

goroutine 1 [running]:
panic(0x624820, 0xc4200e0570)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.main()
	/home/gianluca/Desktop/go-test/main.go:42 +0x554
```

**Comment by aimin** [comment]
I met the same situation, please ask how to solve

**Comment by benbjohnson** [comment]
I'm closing this issue and archiving the repository as phantomjs has been deprecated since 2018. https://github.com/benbjohnson/phantomjs#deprecation-warning
